language: node_js

node_js:
  - 11.10.0
cache:
  directories:
    - node_modules
# env:
#   ci: true

before_install:
  - npm i

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release

      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      # script: 
      #   - npx semantic-release
      # on: master